version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: appflowy_nginx_1
      APP_PORT: 1006
      PROXY_AUTH_ADD: "false"
      PROXY_REDIRECT: |
        location / {
          proxy_pass http://appflowy_web:80;
        }
        location /console {
          proxy_pass http://admin_frontend:3000;
        }
        location /gotrue {
          proxy_pass http://gotrue:9999;
        }
        location /api {
          proxy_pass http://appflowy_cloud:8000;
        }
        location /minio {
          proxy_pass http://minio:9001;
        }
        location /ws {
          proxy_pass http://appflowy_cloud:8000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
        }

  nginx:
    image: nginx:alpine
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${APP_DATA_DIR}/ssl:/etc/nginx/ssl
    depends_on:
      - appflowy_cloud
      - gotrue
      - admin_frontend

  minio:
    image: minio/minio
    environment:
      - MINIO_BROWSER_REDIRECT_URL=${APPFLOWY_BASE_URL}/minio
      - MINIO_ROOT_USER=${APPFLOWY_S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${APPFLOWY_S3_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ${APP_DATA_DIR}/minio:/data

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SUPABASE_PASSWORD=${SUPABASE_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: on-failure

  gotrue:
    image: appflowyinc/gotrue:latest
    environment:
      - GOTRUE_JWT_SECRET=${GOTRUE_JWT_SECRET}
      - DATABASE_URL=${GOTRUE_DATABASE_URL}
      - API_EXTERNAL_URL=${APPFLOWY_BASE_URL}
    depends_on:
      postgres:
        condition: service_healthy

  appflowy_cloud:
    image: appflowyinc/appflowy_cloud:latest
    environment:
      - APPFLOWY_DATABASE_URL=${APPFLOWY_DATABASE_URL}
      - APPFLOWY_REDIS_URI=redis://redis:6379
      - APPFLOWY_S3_ACCESS_KEY=${APPFLOWY_S3_ACCESS_KEY}
      - APPFLOWY_S3_SECRET_KEY=${APPFLOWY_S3_SECRET_KEY}
    depends_on:
      - postgres
      - redis

  admin_frontend:
    image: appflowyinc/admin_frontend:latest
    environment:
      - ADMIN_FRONTEND_REDIS_URL=redis://redis:6379
      - ADMIN_FRONTEND_GOTRUE_URL=http://gotrue:9999
    depends_on:
      - appflowy_cloud

  appflowy_web:
    image: appflowyinc/appflowy_web:latest
    environment:
      - AF_BASE_URL=${APPFLOWY_BASE_URL}
      - AF_GOTRUE_URL=${APPFLOWY_BASE_URL}

volumes:
  postgres:
  minio: