version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dancpluz-whatsapp-web-api_web_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"  # Disable auth for API endpoints

  web:
    image: chrishubert/whatsapp-web-api@sha256:e929c16a970f60350b4974d68a08c5a8cea59124ff97741de2001628b9cc1392  # Add actual SHA256 digest
    user: 1000:1000  # Required non-root user
    restart: on-failure  # Umbrel preferred policy
    stop_grace_period: 1m
    environment:
      - API_KEY=${API_KEY}
      - BASE_WEBHOOK_URL=${BASE_WEBHOOK_URL}
      - MAX_ATTACHMENT_SIZE=5000000
      - SET_MESSAGES_AS_SEEN=TRUE
      - DISABLED_CALLBACKS=auth_failure|authenticated|call|change_state|disconnected|group_join|group_leave|group_update|loading_screen|media_uploaded|message_ack|message_create|message_reaction|message_revoke_everyone|qr|ready|contact_changed
      - ENABLE_SWAGGER_ENDPOINT=TRUE
    volumes:
      - ${APP_DATA_DIR}/sessions:/usr/src/app/sessions
